### ISSUE TITLE
Not work in  Quick Booking

### ISSUE THREAD

**Issue by tung-nt** [PandaDrunkard/ActiveSG#5]
The non-quick booking is working fine but the quick booking from 6am to 8am is not working anymore.
The search avaiable slots return nothing even passed in the date selected, the court id.

**Comment by PandaDrunkard** [comment]
Did you use encrypted password instead of plain password?

**Comment by tung-nt** [comment]
I used encrypted password, I can book without error with the non-quick booking.
Only got problem with the quick booking, cannot see the available slots. The search return page always the same as the quick booking page, no slots available display.

**Comment by PandaDrunkard** [comment]
Fixed in #6 .

**Comment by tung-nt** [comment]
It's working like a charm. Thank you so much
